### ISSUE TITLE
Column order is changed

### ISSUE THREAD

**Issue by CorneeldH** [enningb/eencijfer#6]
* eencijfer version:
* Python version:
* Operating System:

### Description

When the default option of remove pii is enabled, the VAKHAVW changes the order of the columns. Persoonsgebondennummer is moved to just before BurgerServiceNummer and OnderwijsNummer. It seems preferable to keep the order the same (even if they aren't filled). 

Now I'm writing about it, a potential third option could be to pseudomize the identification columns (or add pseudonomize id). Since local id seems to only work if there is an additional mapping table or so?

The same goes for the EV file.

PS, It could also be considered to do a filling value that has the same column type as the 'real' value and just a default value (so 0 for int and a space like " " for characters. Loading the file would then be the same.

Thanks for consideration!

**Comment by enningb** [comment]
Thanks for your suggestions!
First, I think depending on column order is an anti-pattern. You should avoid depending on the order of columns when writing code.
Nonetheless, it seems a minor change to keep the original order (and changing the order of columns is also an anti-pattern). 

The rationale behind the current is this:

- Persoonsgebondennummer is never empty (it is the index for a person). 
- Onderwijsnummer en Burgerservicenummer are sometimes empty (or used to be)
- For the purpose of using the eencijfer, 1 index is enough, so only Persoonsgebondennummer is pseudonimized, the other emptied
- in the package there a 2 scenario's
  - both EV and VAKHV are present: a mapping table is created from EV. The table contains only Persoonsgebondennummer and a randomly created pseudo-id. This mapping table is used for both files
  - only one of EV or VAKHV is present: same as above, unless only VAKH is present, than that is used for creating a mappingtable.

Do you think it is usefull the create pseudo-id's for Onderwijsnummer and Burgerservicenummer?

**Comment by CorneeldH** [comment]
Lot's of anti-patterns to unpack!

It is indeed a question of changing the column orders. I use the output of this package to make synthetic data that can serve as input for this package. This package actually depends completely on column order (which is necessary since there are no columns in the raw data) so now I have to change the column order in my code to negate the changes in column order in this package with the removee pii setting enabled ;-)

For raw data we always do a validation / audit before loading the data in. We always check the column order and type etc, personally that is legit. 

I will check my code later in the pipelines if there are dependencies on column order, sir.

**Comment by enningb** [comment]
Order is preserved with the release of version 2024.4.3
